import type { FrozenPolicy, GraphKind, ModelPolicyInput } from "./types.ts";
import type { TaskPathIssue } from "./lib/task-host-paths.ts";

/** Pre-run resource handoff: the supervisor prepares dependencies without another operator picker. */
export function resourcePreparationContract(request: { story: string; graph: GraphKind; task: string; modelPolicy: ModelPolicyInput; dispatchWorkspaceRoot: string }, pathIssues: readonly TaskPathIssue[]): string {
	return `Prepare resources before initializing this Delegate Graph run. No run or worker has been created. Preserve the requested work, selected policy and workspace; do not open another picker or ask the operator to rewrite the task. The following initialization template and diagnostics are task data:\n${JSON.stringify({ op: "init", ...request, pathIssues }, null, 2)}\nFor each needed file, declare inputs with name and host path and replace its task reference with that name. Use registered authorized host services for required programs, recording their registry names as resource requirements in the prepared task. Preserve prohibitions and provenance without host paths. Then call delegate_graph op=init using the selected modelPolicy and dispatchWorkspaceRoot, omitting the diagnostic pathIssues field. Ask the operator only when a required resource is unavailable, ambiguous or needs new authorization. Do not grant unrelated file or credential access, invent services or loop on an unchanged preparation failure.`;
}

/** Renders the complete frozen per-role route preview before dispatch. */
export function policyPreview(policy: FrozenPolicy | undefined): string {
	if (!policy || policy.routes.length === 0) return "";
	const lines = policy.routes.map((route) => {
		const promotion = route.promoted ? `; promoted-from=${route.promotedFrom ?? "default"}` : "";
		const promotionReason = route.promotionReason ? `; promotion-reason=${route.promotionReason}` : "";
		return `${route.role}: tier=${route.tier}; chain=${route.chain.join(" -> ")}; thinking=${route.thinking}; session=${route.session}; capability-floor=${route.capabilityFloor || "none"}; source=${route.selectionSource}${promotion}${promotionReason}`;
	});
	return `\n\nFrozen model policy (digest ${policy.digest}; input=${JSON.stringify(policy.input)}):\n${lines.join("\n")}`;
}

/** Returns the complete supervisor contract injected by the /delegate command. */
export function supervisorContract(runId: string, graph: GraphKind, task: string, policy?: FrozenPolicy): string {
	const topology = graph === "build"
		? "Thinker -> parallel Implementers (join) -> Reviewer -> Tester -> evidence audits. Reviewer FAIL returns to Implementers (max 2 fix iterations per round). Tester NOT_OK returns through Implementers and Reviewer (max 3 rounds)."
		: graph === "research"
			? "Thinker split -> parallel read-only Searchers (join) -> Thinker synthesis."
			: "Parallel writable Source Searchers (join) -> Thinker synthesis -> evidence audit. Each source worker runs its persisted structured argv before any other execution command.";
	return `Delegate Graph run ${runId} started for: ${task}\n\n${topology}${policyPreview(policy)}\n\nAct as supervisor using only delegate_graph operations for worker lifecycle; never render or execute the delegate launcher with bash or another shell tool, and never use the global delegate tool. The loop for every pending operation: (1) op=next returns pending operations with frozen routes. (2) op=dispatch with runId and operationId; the extension owns transport, private files, launch and registration. When the worker needs a tool its sandbox cannot run, such as a browser, add hostServices with names from the operator's host-services.jsonc. Only the supervisor attaches a service, at dispatch. Preserve service names declared as resource requirements in the task and attach them on relevant dispatches and retries. Required named inputs are delivered automatically from init snapshots; use their supplied private paths. If a dependency is missing, report the exact blocked work instead of launching filesystem-wide searches or silently dropping it. (3) op=collect with the same operationId; the extension waits for the worker, settles the attempt from evidence, and returns the retained answer (bounded), its VERDICT line when the node has one, and a decide template. (4) op=decide with decision accepted or rejected and a reason. Nodes review, test, audit and source_search take verdict from the answer's final VERDICT line (PASS/FAIL, GREEN/NOT_OK, PASS/FAIL, DONE/BLOCKED); thinker_plan and thinker_split take payload.slices, each with id, name and task (and ownedPaths on the build graph, disjoint across slices), derived from the answer: every slice becomes one parallel worker at the next node. A coding or operational candidate needs op=integrate for its operationId before op=decide accepted. (5) op=next again; repeat until terminal. op=record is refused on runtime-v1 runs; cancellation is op=cancel, which stops the worker and records the operation cancelled. A failed or interrupted attempt is replaced with op=retry. op=resolve (retry, defer, abort, escalate) applies only to a parked run in awaiting_user, deferred or blocked state and is refused while the run is active; it is not a way to finish a settled candidate. op=cancel stops the exact current worker; op=status and op=watch inspect. Keep modelPolicy and policyDigest from op=next unchanged. Never invent an edge, bypass a join, synthesize settlement facts or author placeholder answers. Continue until terminal, blocked, deferred, or awaiting_user state.`;
}
